//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class menza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menza()
        {
            this.spremacicas = new HashSet<spremacica>();
        }
    
        public int id_menza { get; set; }
        public string ime { get; set; }
        public Nullable<int> br_mesta { get; set; }
        public int stud_centar_id_stud_centar { get; set; }
    
        public virtual stud_centar stud_centar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spremacica> spremacicas { get; set; }
    }
}
