//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class prijavljuje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prijavljuje()
        {
            this.domars = new HashSet<domar>();
        }
    
        public int stanuje_soba_id_soba { get; set; }
        public string stanuje_student_jmbg { get; set; }
        public int kvar_id_kvar { get; set; }
    
        public virtual kvar kvar { get; set; }
        public virtual stanuje stanuje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domar> domars { get; set; }
    }
}
