//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class radnik
    {
        public string ime { get; set; }
        public string prezime { get; set; }
        public Nullable<int> god_staza { get; set; }
        public int id_radnik { get; set; }
        public int stud_centar_id_stud_centar { get; set; }
    
        public virtual domar domar { get; set; }
        public virtual stud_centar stud_centar { get; set; }
        public virtual spremacica spremacica { get; set; }
    }
}
