//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class soba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public soba()
        {
            this.stanujes = new HashSet<stanuje>();
        }
    
        public int id_soba { get; set; }
        public Nullable<int> broj { get; set; }
        public int stud_dom_id_stud_dom { get; set; }
    
        public virtual stud_dom stud_dom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stanuje> stanujes { get; set; }
    }
}
