//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stud_dom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stud_dom()
        {
            this.sobas = new HashSet<soba>();
        }
    
        public int id_stud_dom { get; set; }
        public string ime { get; set; }
        public Nullable<int> br_soba { get; set; }
        public int stud_centar_id_stud_centar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soba> sobas { get; set; }
        public virtual stud_centar stud_centar { get; set; }
    }
}
