//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentskiCentarEntities : DbContext
    {
        public StudentskiCentarEntities()
            : base("name=StudentskiCentarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<domar> domars { get; set; }
        public virtual DbSet<kvar> kvars { get; set; }
        public virtual DbSet<menza> menzas { get; set; }
        public virtual DbSet<prijavljuje> prijavljujes { get; set; }
        public virtual DbSet<radnik> radniks { get; set; }
        public virtual DbSet<soba> sobas { get; set; }
        public virtual DbSet<spremacica> spremacicas { get; set; }
        public virtual DbSet<stanuje> stanujes { get; set; }
        public virtual DbSet<stud_centar> stud_centar { get; set; }
        public virtual DbSet<stud_dom> stud_dom { get; set; }
        public virtual DbSet<student> students { get; set; }
    }
}
